# zizmor.yml
rules:
  unpinned-uses:
    config:
      policies:
        actions/*: ref-pin
  # Allow the following secrets to be used outside of the env context in a GH agentic workflow file.
  secrets-outside-env:
    config:
      allow:
        - GH_AW_GITHUB_MCP_SERVER_TOKEN
        - GH_AW_GITHUB_TOKEN
        - GH_AW_AGENT_TOKEN