codecov:
  require_ci_to_pass: yes

comment:
  layout: "diff, files"
  behavior: default
  require_changes: true
  require_base: no
  require_head: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 6%
        flags:
          - python
          - javascript
