codecov:
  require_ci_to_pass: yes
  branch: main

comment:
  layout: "diff, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

coverage:
  status:
    project:
      javascript:
        # set to non-blocking until we fix codecov reports https://github.com/canonical-web-and-design/ubuntu.com/issues/11479
        informational: true
        target: auto
        # this allows a 1% drop in code coverage
        threshold: 1%
        flags:
          - javascript
      python:
        # set to non-blocking until we fix codecov reports https://github.com/canonical-web-and-design/ubuntu.com/issues/11479
        informational: true
        target: auto
        # this allows a 1% drop in code coverage
        threshold: 1%
        flags:
          - python
    patch:
      default:
        # set to non-blocking until we fix codecov reports https://github.com/canonical-web-and-design/ubuntu.com/issues/11479
        informational: true
