codecov:
  require_ci_to_pass: yes
  branch: main

comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

flag_management:
  default_rules:
    carryforward: boolean?
    ignore: [path]?
    paths: [path]?
    statuses: [
      name_prefix: string (r"^[\w\-\.]+$")
      type: OR("project", "patch", "changes")
      target: OR("auto", percent)?
      include_changes: OR("auto", percent)?
      threshold: percent?
      **normal status attributes
    ]?
