#! /usr/bin/env bash

set -e

RUN_COMMAND="talisker.gunicorn.gevent webapp.app:app --bind $1 --workers 3 --worker-class gevent --name talisker-`hostname`"

if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    {
        if grep -q docker /proc/1/cgroup 2>/dev/null; then
            echo "Don't use DB inside ./run script"
        else
            alembic upgrade head
        fi
    } || {
        read -p "Database migration failed. Create database from scratch? " -n 1 -r
        if [[ $REPLY =~ ^[Yy] ]]; then
            scripts/clear-database.py
            alembic upgrade head
        else
            exit 1
        fi
    }

    ${RUN_COMMAND} --reload --log-level debug --timeout 9999
else
    alembic upgrade head
    ${RUN_COMMAND}
fi
