#! /usr/bin/env bash

set -e

# Run migrations
{
    alembic upgrade head
} || {
    read -p "Database migration failed. Erase database and try again? " -n 1 -r
    if [[ $REPLY =~ ^[Yy] ]]; then
        scripts/clear-database.py
        alembic upgrade head
    else
        exit 1
    fi
}

if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    echo ""
    echo "= Running talisker with development settings ="
    echo ""
    talisker.gunicorn webapp.app:app --bind $1 --name talisker-`hostname` --reload --log-level debug --timeout 9999
else
    talisker.gunicorn webapp.app:app --bind $1 --name talisker-`hostname` --worker-class sync --workers 5
fi
