server:
  name: "Ubuntu Server"
  description: "Ubuntu server is securely designed, scalable, and supports the most popular hardware and software – making it ideal for your cloud, web, and data center use."
  operatingSystem: "Linux"
  applicationCategory: "OperatingSystem"
  url: "https://ubuntu.com/server"
desktop:
  name: "Ubuntu Desktop"
  description: "Fast, secure, and stylishly simple, the Ubuntu operating system is used by 50 million people worldwide every day."
  operatingSystem: "Linux"
  applicationCategory: "OperatingSystem"
  url: "https://ubuntu.com/desktop"
