module.exports = {
  contributions: "./static/js/src/contributions.js",
  "desktop-statistics": "./static/js/src/desktop-statistics.js",
  tutorials: [
    "./static/js/src/tutorial-list.js",
    "./static/js/src/tutorial.js",
  ],
  forms: "./static/js/src/forms.js",
  "image-download": "./static/js/src/image-download.js",
  main: [
    "url-polyfill",
    "url-search-params-polyfill",
    "./static/js/src/polyfills.js",
    "./static/js/src/contextual-menu.js",
    "./static/js/src/dynamic-contact-form.js",
    "./static/js/src/core.js",
    "./static/js/src/navigation.js",
    "./static/js/src/form-validation.js",
    "./static/js/src/scratch.js",
  ],
  "release-chart": "./static/js/src/release-chart.js",
  tabotronic: "./static/js/src/tabotronic.js",
  appliance: "./static/js/src/appliance.js",
  "tco-calculator": "./static/js/src/tco-calculator.js",
  "ua-payment-modal": "./static/js/src/ua-payment-modal.js",
  "sticky-nav": "./static/js/src/sticky-nav.js",
  imageBuilder: "./static/js/src/imageBuilder.js",
  chassisAnimation: "./static/js/src/chassis-animation.js",
  cve: "./static/js/src/cve/cve.js",
};
