#!/usr/bin/env bash
# Smoke test for scripts/check-links.sh.
#
# Puts a fake `linkchecker` and a no-op `sleep` on PATH, so the real network and
# the retry backoff are never hit. Run with: bash tests/shell/test-check-links.sh

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TARGET="${REPO_ROOT}/scripts/check-links.sh"
CONFIG="${REPO_ROOT}/.linkchecker/live-links/linkcheckerrc"

STUB_DIR="$(mktemp -d)"
trap 'rm -rf "$STUB_DIR"' EXIT

# STUB_EXITS: space-separated exit code per invocation.
# STUB_FAILS: space-separated group per invocation; comma-separated failing
#             URLs within a group, or "-" for none.
cat > "${STUB_DIR}/linkchecker" <<'STUB'
#!/usr/bin/env bash
out=""
prev=""
for arg in "$@"; do
  [ "$prev" = "-F" ] && out="${arg#csv/}"
  prev="$arg"
done

n=$(( $(cat "$STUB_STATE") + 1 ))
echo "$n" > "$STUB_STATE"
printf '%s\n' "$*" >> "$STUB_LOG"

read -ra exits <<< "$STUB_EXITS"
read -ra groups <<< "$STUB_FAILS"
code="${exits[$((n - 1))]:-0}"
fails="${groups[$((n - 1))]:--}"

# `urlname` is deliberately relative and `url` absolute, as real LinkChecker
# emits them, so the test pins which column extract_failed reads.
if [ -n "$out" ]; then
  {
    echo "# generated by fake linkchecker"
    echo "urlname;parentname;baseref;result;valid;url"
    if [ "$fails" != "-" ]; then
      IFS=',' read -ra urls <<< "$fails"
      for u in "${urls[@]}"; do
        echo "${u#https://example.com};https://example.com;;404 Not Found;False;${u}"
      done
    fi
    echo "/ok;https://example.com;;200 OK;True;https://example.com/ok"
  } > "$out"
fi

exit "$code"
STUB
chmod +x "${STUB_DIR}/linkchecker"

printf '#!/usr/bin/env bash\nexit 0\n' > "${STUB_DIR}/sleep"
chmod +x "${STUB_DIR}/sleep"

export STUB_STATE="${STUB_DIR}/count"
export STUB_LOG="${STUB_DIR}/log"

failures=0
status=0
output=""

run_case() {
  export STUB_EXITS="$1"
  export STUB_FAILS="$2"
  echo 0 > "$STUB_STATE"
  : > "$STUB_LOG"
  output="$(PATH="${STUB_DIR}:${PATH}" bash "$TARGET" "$CONFIG" https://example.com 2>&1)"
  status=$?
}

check() {
  local name="$1" expected="$2" actual="$3"
  if [ "$expected" = "$actual" ]; then
    echo "ok   - ${name}"
  else
    echo "FAIL - ${name}: expected '${expected}', got '${actual}'"
    printf '%s\n' "$output" | sed 's/^/       | /'
    failures=$((failures + 1))
  fi
}

contains() {
  local name="$1" needle="$2"
  case "$output" in
    *"$needle"*) echo "ok   - ${name}" ;;
    *)
      echo "FAIL - ${name}: output missing '${needle}'"
      printf '%s\n' "$output" | sed 's/^/       | /'
      failures=$((failures + 1))
      ;;
  esac
}

# 1. Clean run.
run_case "0" "-"
check "clean run exits 0" 0 "$status"
contains "clean run reports success" "No broken links found."

# 2. Transient failure that clears on the first retry.
run_case "1 0" "https://example.com/flaky -"
check "transient failure exits 0" 0 "$status"
contains "transient failure reports recovery" "resolved on attempt 1"

# 3. Persistent failure: initial run + 3 retries, then give up.
run_case "1 1 1 1" "https://example.com/dead https://example.com/dead https://example.com/dead https://example.com/dead"
check "persistent failure exits 1" 1 "$status"
contains "persistent failure lists the URL" "https://example.com/dead"
check "persistent failure uses all attempts" 4 "$(cat "$STUB_STATE")"

# 4. Unexpected linkchecker exit code is not treated as a broken link.
run_case "3" "-"
check "runtime error exits 2" 2 "$status"
contains "runtime error is reported" "LinkChecker failed unexpectedly"

# 5. Duplicate failures are de-duplicated before the recheck.
run_case "1 0" "https://example.com/a,https://example.com/a,https://example.com/b -"
check "dedup run exits 0" 0 "$status"
check "recheck receives 1 copy of /a" 1 "$(sed -n 2p "$STUB_LOG" | grep -o 'https://example\.com/a\b' | wc -l | tr -d ' ')"
contains "recheck reports 2 links" "rechecking 2 link(s)"

# 6. Missing arguments print usage and exit 2.
output="$(PATH="${STUB_DIR}:${PATH}" bash "$TARGET" "$CONFIG" 2>&1)"
status=$?
check "missing URL exits 2" 2 "$status"
contains "missing URL prints usage" "Usage:"

echo
if [ "$failures" -eq 0 ]; then
  echo "All check-links.sh tests passed."
else
  echo "${failures} test(s) failed."
fi
exit $(( failures > 0 ))
