domain: ubuntu.com

image: prod-comms.docker-registry.canonical.com/ubuntu.com

env:
  - name: DATABASE_URL
    secretKeyRef:
      key: database_url
      name: usn-db-url

  - name: SEARCH_API_KEY
    secretKeyRef:
      key: google-custom-search-key
      name: google-api

  - name: LAUNCHPAD_IMAGE_BUILD_USER
    secretKeyRef:
      key: user
      name: launchpad-imagebuild

  - name: LAUNCHPAD_IMAGE_BUILD_TOKEN
    secretKeyRef:
      key: token
      name: launchpad-imagebuild

  - name: LAUNCHPAD_IMAGE_BUILD_SECRET
    secretKeyRef:
      key: secret
      name: launchpad-imagebuild

  - name: LAUNCHPAD_IMAGE_BUILD_AUTH_CONSUMER
    secretKeyRef:
      key: auth-consumer
      name: launchpad-imagebuild

  - name: SENTRY_DSN
    value: https://0293bb7fc3104e56bafd2422e155790c@sentry.is.canonical.com//13

memoryLimit: 512Mi

extraHosts:
  - domain: ubuntu.net
  - domain: tutorials.ubuntu.com
  - domain: blog.ubuntu.com
  - domain: insights.ubuntu.com
  - domain: ubunut.com
  - domain: ubuntulinux.org
  - domain: download.ubuntu.com
  - domain: apps.ubuntu.com
  - domain: cloud.ubuntu.com
  - domain: jobs.ubuntu.com
  - domain: release-blog.ubuntu.com
  - domain: tour.ubuntu.com
  - domain: webapps.ubuntu.com
  - domain: ubuntuserver.org
  - domain: developer.ubuntu.com

# Overrides for production
production:
  replicas: 5

  routes:
    - paths: [/blog]
      name: ubuntu-com-blog
      app_name: ubuntu.com-blog
      image: prod-comms.docker-registry.canonical.com/ubuntu.com
      replicas: 5
      memoryLimit: 512Mi
      env:
        - name: DATABASE_URL
          secretKeyRef:
            key: database_url
            name: usn-db-url

        - name: SEARCH_API_KEY
          secretKeyRef:
            key: google-custom-search-key
            name: google-api

        - name: SENTRY_DSN
          value: https://0293bb7fc3104e56bafd2422e155790c@sentry.is.canonical.com//13

    - paths: [/tutorials]
      name: ubuntu-com-tutorials
      app_name: ubuntu.com-tutorials
      image: prod-comms.docker-registry.canonical.com/ubuntu.com
      replicas: 5
      memoryLimit: 512Mi
      env:
        - name: DATABASE_URL
          secretKeyRef:
            key: database_url
            name: usn-db-url

        - name: SEARCH_API_KEY
          secretKeyRef:
            key: google-custom-search-key
            name: google-api

        - name: SENTRY_DSN
          value: https://0293bb7fc3104e56bafd2422e155790c@sentry.is.canonical.com//13

  nginxConfigurationSnippet: |
    if ($host = 'apps.ubuntu.com' ) {
      rewrite ^ https://snapcraft.io/ permanent;
    }
    if ($host = 'cloud.ubuntu.com' ) {
      rewrite ^ https://ubuntu.com/public-cloud$request_uri? permanent;
    }
    if ($host = 'download.ubuntu.com' ) {
      rewrite ^ https://ubuntu.com/download$request_uri? permanent;
    }
    if ($host = 'tutorials.ubuntu.com' ) {
      rewrite ^ https://ubuntu.com/tutorials$request_uri? permanent;
    }
    if ($host = 'blog.ubuntu.com' ) {
      rewrite ^ https://ubuntu.com/blog$request_uri? permanent;
    }
    if ($host = 'insights.ubuntu.com' ) {
      rewrite ^ https://ubuntu.com/blog$request_uri? permanent;
    }
    if ($host = 'jobs.ubuntu.com' ) {
      rewrite ^ https://canonical.com/careers$request_uri? permanent;
    }
    if ($host = 'release-blog.ubuntu.com' ) {
      rewrite ^ https://ubuntu.com/blog$request_uri? permanent;
    }
    if ($host = 'tour.ubuntu.com' ) {
      rewrite ^ https://ubuntu.com/desktop/features$request_uri? permanent;
    }
    if ($host = 'webapps.ubuntu.com' ) {
      rewrite ^ https://partners.ubuntu.com/programmes/software$request_uri? permanent;
    }
    if ($host = 'developer.ubuntu.com' ) {
      rewrite ^ https://ubuntu.com/developer$request_uri? permanent;
    }
    if ($host = 'ubuntuserver.org' ) {
      rewrite ^ https://ubuntu.com/server$request_uri? permanent;
    }
    if ($host != 'ubuntu.com' ) {
      rewrite ^ https://ubuntu.com$request_uri? permanent;
    }
    if ($uri = '/blog/latest-news') {
      add_header 'Access-Control-Allow-Origin' '*';
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";

  nginxServerSnippet: |
    location /blog/wp-json/wp/v2/ {
      proxy_pass https://admin.insights.ubuntu.com/wp-json/wp/v2/;
    }
    location /wp-content/uploads/ {
      proxy_pass https://admin.insights.ubuntu.com/wp-content/uploads/;
    }

# Overrides for staging
staging:
  replicas: 3

  routes:
    - paths: [/blog]
      name: ubuntu-com-blog
      app_name: ubuntu.com-blog
      image: prod-comms.docker-registry.canonical.com/ubuntu.com
      replicas: 3
      memoryLimit: 512Mi
      env:
        - name: DATABASE_URL
          secretKeyRef:
            key: database_url
            name: usn-db-url

        - name: SEARCH_API_KEY
          secretKeyRef:
            key: google-custom-search-key
            name: google-api

        - name: SENTRY_DSN
          value: https://0293bb7fc3104e56bafd2422e155790c@sentry.is.canonical.com//13

    - paths: [/tutorials]
      name: ubuntu-com-tutorials
      app_name: ubuntu.com-tutorials
      image: prod-comms.docker-registry.canonical.com/ubuntu.com
      replicas: 3
      memoryLimit: 512Mi
      env:
        - name: DATABASE_URL
          secretKeyRef:
            key: database_url
            name: usn-db-url

        - name: SEARCH_API_KEY
          secretKeyRef:
            key: google-custom-search-key
            name: google-api

        - name: SENTRY_DSN
          value: https://0293bb7fc3104e56bafd2422e155790c@sentry.is.canonical.com//13

  nginxConfigurationSnippet: |
    if ($host = 'staging.cloud.ubuntu.com' ) {
      rewrite ^ https://staging.ubuntu.com/public-cloud$request_uri? permanent;
    }
    if ($host = 'tutorials.staging.ubuntu.com' ) {
      rewrite ^ https://staging.ubuntu.com/tutorials$request_uri? permanent;
    }
    if ($host = 'blog.staging.ubuntu.com' ) {
      rewrite ^ https://staging.ubuntu.com/blog$request_uri? permanent;
    }
    if ($host = 'insights.staging.ubuntu.com' ) {
      rewrite ^ https://staging.ubuntu.com/blog$request_uri? permanent;
    }
    if ($host != 'staging.ubuntu.com' ) {
      rewrite ^ https://staging.ubuntu.com$request_uri? permanent;
    }
    if ($uri = '/blog/latest-news') {
      add_header 'Access-Control-Allow-Origin' '*';
    }
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";

  nginxServerSnippet: |
    location /blog/wp-json/wp/v2/ {
      proxy_pass https://admin.insights.ubuntu.com/wp-json/wp/v2/;
    }
    location /wp-content/uploads/ {
      proxy_pass https://admin.insights.ubuntu.com/wp-content/uploads/;
    }
