#!/bin/bash

echo "Running lint-scss"
if ! yarn lint-scss; then
  echo "lint-scss failed. Push denied."
  exit 1
fi

echo "Running lint-js"
if ! yarn lint-js; then
  echo "lint-js failed. Push denied."
  exit 1
fi

echo "Running lint-python"
if ! yarn lint-python; then
  echo "lint-python failed. Push denied."
  exit 1
fi

echo "Running lint-html"
if ! ./scripts/djlint lint --cached; then
  echo "lint-html failed. Push denied."
  exit 1
fi

exit 0
