#!/bin/bash

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$local_sha" = "0000000000000000000000000000000000000000000" ]; then
    continue
  fi

  if [ "$remote_sha" = "0000000000000000000000000000000000000000000" ]; then
    range="${local_sha}"
  else
    range="${remote_sha}..${local_sha}"
  fi

  changed_files=$(git diff --name-only "$range")

  error_flag=0

  if echo "$changed_files" | grep -qE '\.scss$'; then
    echo "Running lint-scss..."
    if ! yarn lint-scss; then
      echo "lint-scss failed."
      error_flag=1
    fi
  fi

  if echo "$changed_files" | grep -qE '\.js$'; then
    echo "Running lint-js..."
    if ! yarn lint-js; then
      echo "lint-js failed."
      error_flag=1
    fi
  fi

  if echo "$changed_files" | grep -qE '\.py$'; then
    echo "Running lint-python..."
    if ! yarn lint-python; then
      echo "lint-python failed."
      error_flag=1
    fi
  fi

  if echo "$changed_files" | grep -qE '\.html$'; then
    echo "Running lint-html..."
    if ! ./scripts/djlint lint --committed; then
      echo "lint-html failed."
      error_flag=1
    fi
  fi

done

if [ "$error_flag" -eq 1 ]; then
  echo "❌ One or more linters failed. Push denied."
  exit 1
else
  echo "✅ All linters passed. Push allowed."
  exit 0
fi
