"""CVE migrations

Revision ID: 0a701c4a0e2a
Revises: c2bc5f0b027d
Create Date: 2020-05-15 16:25:40.789877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a701c4a0e2a"
down_revision = "c2bc5f0b027d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("launchpad", sa.String(), nullable=True),
        sa.Column("ubuntu", sa.String(), nullable=True),
        sa.Column("debian", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "package_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("status_description", sa.String(), nullable=True),
        sa.Column("cve_id", sa.String(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("release_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cve_id"], ["cve.id"]),
        sa.ForeignKeyConstraint(["package_id"], ["package.id"]),
        sa.ForeignKeyConstraint(["release_id"], ["release.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("notice_references")
    op.drop_table("reference")
    op.add_column("cve", sa.Column("approved_by", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("assigned_to", sa.String(), nullable=True))
    op.add_column(
        "cve", sa.Column("bugs", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column("cve", sa.Column("crd", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("cvss", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "cve", sa.Column("discovered_by", sa.String(), nullable=True)
    )
    op.add_column(
        "cve", sa.Column("last_updated_date", sa.DateTime(), nullable=True)
    )
    op.add_column("cve", sa.Column("mitigation", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("notes", sa.JSON(), nullable=True))
    op.add_column("cve", sa.Column("priority", sa.String(), nullable=True))
    op.add_column(
        "cve", sa.Column("public_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "cve", sa.Column("public_date_usn", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "cve", sa.Column("references", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column("cve", sa.Column("status", sa.String(), nullable=True))
    op.add_column(
        "cve", sa.Column("ubuntu_description", sa.String(), nullable=True)
    )
    op.add_column(
        "notice", sa.Column("references", sa.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notice", "references")
    op.drop_column("cve", "ubuntu_description")
    op.drop_column("cve", "status")
    op.drop_column("cve", "references")
    op.drop_column("cve", "public_date_usn")
    op.drop_column("cve", "public_date")
    op.drop_column("cve", "priority")
    op.drop_column("cve", "notes")
    op.drop_column("cve", "mitigation")
    op.drop_column("cve", "last_updated_date")
    op.drop_column("cve", "discovered_by")
    op.drop_column("cve", "description")
    op.drop_column("cve", "cvss")
    op.drop_column("cve", "crd")
    op.drop_column("cve", "bugs")
    op.drop_column("cve", "assigned_to")
    op.drop_column("cve", "approved_by")
    op.create_table(
        "notice_references",
        sa.Column(
            "notice_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "reference_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notice.id"],
            name="notice_references_notice_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["reference.id"],
            name="notice_references_reference_id_fkey",
        ),
    )
    op.create_table(
        "reference",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uri", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="reference_pkey"),
    )
    op.drop_table("package_status")
    op.drop_table("package")
    # ### end Alembic commands ###
