"""Add release expiry dates

Revision ID: 11d099874744
Revises: 566647193540
Create Date: 2020-04-15 11:46:45.130384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11d099874744"
down_revision = "566647193540"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "release", sa.Column("esm_expires", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "release", sa.Column("support_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release", "support_expires")
    op.drop_column("release", "esm_expires")
    # ### end Alembic commands ###
