"""“release_update”

Revision ID: 566647193540
Revises: e8760725610a
Create Date: 2020-04-14 14:59:01.861169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "566647193540"
down_revision = "e8760725610a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "release", sa.Column("development", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "release", sa.Column("release_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release", "release_date")
    op.drop_column("release", "development")
    # ### end Alembic commands ###
