"""“cve_migration”

Revision ID: 998c7f484953
Revises: bd090227c8fe
Create Date: 2020-04-06 17:38:11.190588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "998c7f484953"
down_revision = "bd090227c8fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cve", sa.Column("last_updated_date", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cve", "last_updated_date")
    # ### end Alembic commands ###
