"""“cve_migration”

Revision ID: a88c140f4ed1
Revises: e8760725610a
Create Date: 2020-04-16 00:55:36.066624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a88c140f4ed1"
down_revision = "e8760725610a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bug",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uri", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cve_reference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uri", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "package",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("ubuntu", sa.String(), nullable=True),
        sa.Column("debian", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "package_release_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("status_description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cve_bugs",
        sa.Column("cve_id", sa.String(), nullable=True),
        sa.Column("bug_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["bug_id"], ["bug.id"],),
        sa.ForeignKeyConstraint(["cve_id"], ["cve.id"],),
    )
    op.create_table(
        "cve_package_release_status",
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("package_release_status_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["package_id"], ["package.id"],),
        sa.ForeignKeyConstraint(
            ["package_release_status_id"], ["package_release_status.id"],
        ),
    )
    op.create_table(
        "cve_packages",
        sa.Column("cve_id", sa.String(), nullable=True),
        sa.Column("cve_packages", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cve_id"], ["cve.id"],),
        sa.ForeignKeyConstraint(["cve_packages"], ["package.id"],),
    )
    op.create_table(
        "cve_references",
        sa.Column("cve_id", sa.String(), nullable=True),
        sa.Column("cve_reference_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cve_id"], ["cve.id"],),
        sa.ForeignKeyConstraint(["cve_reference_id"], ["cve_reference.id"],),
    )
    op.create_table(
        "cve_releases",
        sa.Column("release_id", sa.Integer(), nullable=True),
        sa.Column("package_release_status_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["package_release_status_id"], ["package_release_status.id"],
        ),
        sa.ForeignKeyConstraint(["release_id"], ["release.id"],),
    )
    op.add_column("cve", sa.Column("approved_by", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("assigned_to", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("crd", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("cvss", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "cve", sa.Column("discovered_by", sa.String(), nullable=True)
    )
    op.add_column(
        "cve", sa.Column("last_updated_date", sa.DateTime(), nullable=True)
    )
    op.add_column("cve", sa.Column("mitigation", sa.String(), nullable=True))
    op.add_column("cve", sa.Column("notes", sa.JSON(), nullable=True))
    op.add_column("cve", sa.Column("priority", sa.String(), nullable=True))
    op.add_column(
        "cve", sa.Column("public_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "cve", sa.Column("public_date_usn", sa.DateTime(), nullable=True)
    )
    op.add_column("cve", sa.Column("status", sa.String(), nullable=True))
    op.add_column(
        "cve", sa.Column("ubuntu_description", sa.String(), nullable=True)
    )
    op.add_column(
        "release", sa.Column("development", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "release", sa.Column("esm_expires", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "release", sa.Column("release_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "release", sa.Column("support_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release", "support_expires")
    op.drop_column("release", "release_date")
    op.drop_column("release", "esm_expires")
    op.drop_column("release", "development")
    op.drop_column("cve", "ubuntu_description")
    op.drop_column("cve", "status")
    op.drop_column("cve", "public_date_usn")
    op.drop_column("cve", "public_date")
    op.drop_column("cve", "priority")
    op.drop_column("cve", "notes")
    op.drop_column("cve", "mitigation")
    op.drop_column("cve", "last_updated_date")
    op.drop_column("cve", "discovered_by")
    op.drop_column("cve", "description")
    op.drop_column("cve", "cvss")
    op.drop_column("cve", "crd")
    op.drop_column("cve", "assigned_to")
    op.drop_column("cve", "approved_by")
    op.drop_table("cve_releases")
    op.drop_table("cve_references")
    op.drop_table("cve_packages")
    op.drop_table("cve_package_release_status")
    op.drop_table("cve_bugs")
    op.drop_table("package_release_status")
    op.drop_table("package")
    op.drop_table("cve_reference")
    op.drop_table("bug")
    # ### end Alembic commands ###
