"""Add release support expiry dates

Revision ID: c2bc5f0b027d
Revises: 566647193540
Create Date: 2020-04-15 17:28:32.715715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2bc5f0b027d"
down_revision = "566647193540"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "release", sa.Column("esm_expires", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "release", sa.Column("support_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release", "support_expires")
    op.drop_column("release", "esm_expires")
    # ### end Alembic commands ###
