"""“cve_migration”

Revision ID: cbe9e464a0b4
Revises: 7e59f679768b
Create Date: 2020-04-01 15:42:19.727676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe9e464a0b4'
down_revision = '7e59f679768b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###