"""firstmigration

Revision ID: e8760725610a
Revises:
Create Date: 2020-03-12 11:04:29.321360

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e8760725610a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cve",
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notice",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("published", sa.DateTime(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("isummary", sa.String(), nullable=True),
        sa.Column("details", sa.String(), nullable=True),
        sa.Column("instructions", sa.String(), nullable=True),
        sa.Column("packages", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uri", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "release",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("codename", sa.String(), nullable=True),
        sa.Column("lts", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codename"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "notice_cves",
        sa.Column("notice_id", sa.String(), nullable=True),
        sa.Column("cve_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["cve_id"], ["cve.id"]),
        sa.ForeignKeyConstraint(["notice_id"], ["notice.id"]),
    )
    op.create_table(
        "notice_references",
        sa.Column("notice_id", sa.String(), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["notice_id"], ["notice.id"]),
        sa.ForeignKeyConstraint(["reference_id"], ["reference.id"]),
    )
    op.create_table(
        "notice_releases",
        sa.Column("notice_id", sa.String(), nullable=True),
        sa.Column("release_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["notice_id"], ["notice.id"]),
        sa.ForeignKeyConstraint(["release_id"], ["release.id"]),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notice_releases")
    op.drop_table("notice_references")
    op.drop_table("notice_cves")
    op.drop_table("release")
    op.drop_table("reference")
    op.drop_table("notice")
    op.drop_table("cve")
    # ### end Alembic commands ###
