#!/bin/bash

lint_html() {
  local diff_option=$1
  if [ "$diff_option" == "--cached" ]; then
    CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E 'templates/.*\.html' || true)
  elif [ "$diff_option" == "--committed" ]; then
    CHANGED_FILES=$(git diff HEAD~1 --name-only --diff-filter=ACM | grep -E 'templates/.*\.html' || true)
  else
    CHANGED_FILES=$(git diff --name-only --diff-filter=ACM | grep -E 'templates/.*\.html' || true)
    STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E 'templates/.*\.html' || true)
    CHANGED_FILES=$(echo -e "$CHANGED_FILES\n$STAGED_FILES" | sort -u)
  fi

  if [ -n "$CHANGED_FILES" ]; then
    printf "Linting HTML files: \n$CHANGED_FILES\n"
    djlint $CHANGED_FILES --lint --profile=jinja
  else
    printf "No HTML files to lint\n"
  fi
}

format_html() {
  local diff_option=$1
  if [ "$diff_option" == "--cached" ]; then
    CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E 'templates/.*\.html' || true)
  else
    CHANGED_FILES=$(git diff --name-only --diff-filter=ACM | grep -E 'templates/.*\.html' || true)
    STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E 'templates/.*\.html' || true)
    CHANGED_FILES=$(echo -e "$CHANGED_FILES\n$STAGED_FILES" | sort -u)
  fi

  if [ -n "$CHANGED_FILES" ]; then
    printf "Formatting HTML files: \n$CHANGED_FILES\n"
    djlint $CHANGED_FILES --reformat --profile=jinja
  else
    printf "No HTML files to format\n"
  fi
}

case "$1" in
  lint)
    lint_html "$2"
    ;;
  format)
    format_html "$2"
    ;;
  *)
    echo "Usage: $0 {lint|format} [--cached]"
    exit 1
    ;;
esac
