name: Setup Taskfile
description: Install Taskfile at the pinned version
runs:
  using: composite
  steps:
    - uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
      with:
        version: 3.40.0
