name: Bandit

on:
  workflow_dispatch:
  schedule:
    - cron: "20 7 * * 1" # every Monday at 07:20 UTC

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@67a458d90fa11fb1463e91e7f4c8f068b5863c7f # v1.0.1

      - name: Send message on failure
        env:
          BOT_URL: ${{ secrets.BOT_URL }}
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" $BOT_URL?room=web-alerts
