name: Cypress checks / PR
env:
  SECRET_KEY: insecure_test_key
  DATABASE_URL: postgresql://postgres@localhost:5432/postgres
  PORT: 8001
  CONTRACTS_API_URL: https://contracts.staging.canonical.com
  STRIPE_PUBLISHABLE_KEY: pk_test_yndN9H0GcJffPe0W58Nm64cM00riYG4N46
  CAPTCHA_TESTING_API_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  MARKETO_API_CLIENT: ${{secrets.MARKETO_API_CLIENT}}
  MARKETO_API_SECRET: ${{secrets.MARKETO_API_SECRET}}

on: pull_request

jobs:
  run-cypress:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    if: github.repository == 'canonical-web-and-design/ubuntu.com'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: UBUNTU_USERNAME=peter.makowski+cy@canonical.com,UBUNTU_PASSWORD=jibfdq5hmq
          build: yarn run build
          start: yarn run serve
          wait-on: "http://0.0.0.0:8001/_status/check"
          wait-on-timeout: 180
          browser: chrome
          config-file: tests/cypress/cypress.json
          config: baseUrl=http://0.0.0.0:8001
