name: Percy testing on PRs from forks
run-name: "Testing Percy on fork PR #${{ github.event.pull_request.number }}"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  pull-requests: read

jobs:
  snapshot:
    name: Take Percy snapshots
    runs-on: ubuntu-latest
    # Ensure we only run for forks (internal PRs use a different workflow)
    if: github.event.pull_request.head.repo.full_name != github.repository

    # The environment "percy-testing" handles the approval gate
    environment: percy-testing

    steps:
      - name: Checkout Trusted Action
        uses: actions/checkout@v4
        with:
          path: trusted-logic
          persist-credentials: false

      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: untrusted-pr-code
          persist-credentials: false

      - uses: ./trusted-logic/.github/actions/percy-snapshot
        with:
          project_root: ./untrusted-pr-code
          pr_number: ${{ github.event.pull_request.number }}
          branch_name: ${{ github.event.pull_request.head.ref }}
          commitsh: ${{ github.event.pull_request.head.sha }}
          percy_token_write: ${{ secrets.PERCY_TOKEN_WRITE }}
