name: Percy testing on PRs from forks
run-name: "Testing Percy on fork PR #${{ github.event.pull_request.number }}"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  pull-requests: read

jobs:
  snapshot:
    name: Take Percy snapshots
    runs-on: ubuntu-latest
    # Ensure we only run for forks (internal PRs use a different workflow)
    if: github.event.pull_request.head.repo.full_name != github.repository

    # The environment "percy-testing" handles the approval gate
    environment: percy-testing

    steps:
      - name: Checkout Trusted Action
        uses: actions/checkout@v4
        with:
          path: trusted-logic
          persist-credentials: false

      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: untrusted-pr-code
          persist-credentials: false

      - name: Get merge base commit SHA
        id: base_commit
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
          cd trusted-logic
          git fetch origin "$BASE_REF"
          git fetch "${{ github.event.pull_request.head.repo.clone_url }}" "${{ github.event.pull_request.head.ref }}"
          echo "sha=$(git merge-base FETCH_HEAD origin/$BASE_REF)" >> $GITHUB_OUTPUT

      - uses: ./trusted-logic/.github/actions/percy-snapshot
        with:
          project_root: ./untrusted-pr-code
          base_ref: ${{ github.base_ref }}
          base_commit: ${{ steps.base_commit.outputs.sha }}
          pr_number: ${{ github.event.pull_request.number }}
          branch_name: ${{ github.event.pull_request.head.ref }}
          commitsh: ${{ github.event.pull_request.head.sha }}
          percy_token_write: ${{ secrets.PERCY_TOKEN_WRITE }}
