name: Performance checks on ubuntu.com

on: [push]

env:
  THRESHOLD: 70

jobs:
  perf-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Running performance checks on the homepage
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the desktop overview page
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/desktop"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the download overview page
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/download"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the blog
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/blog"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the openstack overview
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/openstack"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the kubernetes overview
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/kubernetes"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the managed overview
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/managed"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the ai overview
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/ai"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the robotics overview
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/robotics"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the core overview
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/core"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the cloud overview
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/cloud"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on the tutorials overview
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/tutorials"
          threshold: $THRESHOLD
          strategy: desktop
      - name: Running performance checks on a tutorial
        continue-on-error: true
        uses: jakepartusch/psi-action@v1.3
        with:
          key: ${{ secrets.PSI_API_KEY }}
          url: "https://ubuntu.com/tutorials/how-to-upgrade-ubuntu-lts-to-ubuntu-pro-on-aws-using-aws-license-manager#1-overview"
          threshold: $THRESHOLD
          strategy: desktop
      # - name: Send message on failure
      #   if: failure()
      #   run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=web--design
